export const data = [
  {
    header: 'пробка на мира',
    description: 'Вечер для двоих',
    text: '-50%',
    type: 'скидка',
    img: 'wine',
  },
  {
    header: 'кино и немцы',
    description: 'бесплатный бокал пива',
    text: 'варвар',
    type: 'промокод',
    img: 'beer',
  },
  {
    header: 'valery cakes',
    description: 'Торт',
    text: '30%',
    type: 'скидка',
    img: 'cake',
  },
  {
    header: 'sushi sell',
    description: 'Набор “Праздник”',
    text: '45%',
    type: 'скидка',
    img: 'sushi',
  },
  {
    header: 'mangosteen',
    description: 'Фрукт в подарок',
    text: 'J130',
    type: 'купон',
    img: 'fruit',
  },
  {
    header: 'теленок табака',
    description: 'Стейк “Мачете”',
    text: '20%',
    type: 'скидка',
    img: 'meat',
  },
  {
    header: 'fire food',
    description: 'Вторая шаурма в подарок',
    text: 'ОГОНЬ',
    type: 'промокод',
    img: 'roll',
  },
  {
    header: 'aroma cremeria',
    description: 'Джелато “Пармезан”',
    text: '20%',
    type: 'скидка',
    img: 'ice',
  },
  {
    header: 'пробка на мира',
    description: 'Вечер для двоих',
    text: 'J130',
    type: 'купон',
    img: 'wine',
  },
  {
    header: 'Кино и немцы',
    description: 'Бесплатный бокал пива',
    text: 'ВАРВАР',
    type: 'промокод',
    img: 'beer',
  },
  {
    header: 'VALERY CAKES',
    description: 'Торт',
    text: '30%',
    type: 'скидка',
    img: 'cake',
  },
  {
    header: 'sushi sell',
    description: 'Набор “Праздник”',
    text: '45%',
    type: 'скидка',
    img: 'sushi',
  },
];
